LIG/urls.py
from django.urls import path
from . import views

app_name = 'LIG'

urlpatterns = [
    path('', views.index, name='index'),
    path('cursos/', views.cursos_list, name='cursos_list'),
    path('curso/<int:curso_id>/', views.curso_detail, name='curso_detail'),
    path('disciplinas/', views.disciplinas_list, name='disciplinas_list'),
    path('disciplina/<int:disciplina_id>/', views.disciplina_detail, name='disciplina_detail'),
    path('projeto/<int:projeto_id>/', views.projeto_detail, name='projeto_detail'),
    path('cursos/novo', views.novo_curso_view,name="novo_curso"),
    path('cursos/<int:curso_id>/edita', views.edita_curso_view,name="edita_curso"),
    path('cursos/<int:curso_id>/apaga', views.apaga_curso_view,name="apaga_curso"),
]

artigos/urls.py
from django.urls import path
from . import views

app_name = 'artigos'

urlpatterns = [
    path('', views.layout_view, name='layout'),
    path('autores/', views.autores_view, name='autores'),
    path('autores/<int:autor_id>/', views.autor_detalhes_view, name='autor_detalhes'),  # Nova rota
    path('artigos/', views.artigos_view, name='artigos'),
    path('adicionar_autor/', views.adicionar_autor, name='adicionar_autor'),
    path('editar_autor/<int:autor_id>/', views.editar_autor, name='editar_autor'),
    path('excluir_autor/<int:autor_id>/', views.excluir_autor, name='excluir_autor'),
    path('adicionar_artigo/', views.adicionar_artigo, name='adicionar_artigo'),
    path('editar_artigo/<int:artigo_id>/', views.editar_artigo, name='editar_artigo'),
    path('excluir_artigo/<int:artigo_id>/', views.excluir_artigo, name='excluir_artigo'),
]

autenticacao/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'autenticacao'


urlpatterns = [
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),


    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/custom_password_reset_form.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/custom_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/custom_password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/custom_password_reset_complete.html'), name='password_reset_complete'),
]

bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('', views.bandas_list, name='bandas_list'),
    path('banda/<int:pk>/', views.banda_detail, name='banda'),
    path('album/<int:pk>/', views.album_detail, name='album'),
    path('banda/novo/', views.bandas_create, name='banda_create'),
    path('banda/editar/<int:pk>/', views.bandas_update, name='banda_update'),
    path('banda/excluir/<int:pk>/', views.bandas_delete, name='banda_delete'),
    path('album/novo/', views.albuns_create, name='album_create'),
    path('album/editar/<int:pk>/', views.albuns_update, name='album_update'),
    path('album/excluir/<int:pk>/', views.albuns_delete, name='album_delete'),
    path('musica/novo/', views.musicas_create, name='musica_create'),
    path('musica/editar/<int:pk>/', views.musicas_update, name='musica_update'),
    path('musica/excluir/<int:pk>/', views.musicas_delete, name='musica_delete'),
    path('capa-fundo/', views.capa_fundo_update, name='capa_fundo_update'),
]

meteo/urls.py
from django.urls import path
from .views import lisbon_weather, meteo_home, weather_forecast



app_name = 'meteo'

urlpatterns = [
    path('', meteo_home, name='home'),
    path('lisbon/', lisbon_weather, name='lisbon_weather'),
    path('forecast/', weather_forecast, name='weather_forecast'),


]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('mebyme/', views.mebyme, name='mebyme'),
    path('sobre/', views.sobre, name='mebyme_tech'),
]

python_inicio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('novaapp/', include('novaapp.urls')),
    path('bandas/',include('bandas.urls')),
    path('artigos/',include('artigos.urls')),
    path('festivais/',include('festivais.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('LIG/', include('LIG.urls')),
    path('portfolio', include('portfolio.urls')),
    path('meteo', include('meteo.urls')),

]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render
import requests


def Icon():
    previsao_url = "https://api.ipma.pt/open-data/forecast/meteorology/cities/daily/1110600.json"
    previsao_response = requests.get(previsao_url)
    previsao_data = previsao_response.json()
    hoje_previsao = previsao_data['data'][0]

    id_weather_type = hoje_previsao['idWeatherType']
    icon_url = f"/static/meteo/icons/icons_ipma_weather/w_ic_d_{id_weather_type:02d}anim.svg"

    return icon_url

def landing_page(request):
    icon_url = Icon()
    context = {
        'icon_url': icon_url,
    }
    return render(request, 'portfolio/landing_page.html', context)

def mebyme(request):
    return render(request, 'portfolio/mebyme.html')

def sobre(request):
    return render(request, 'portfolio/mebyme_tech.html')

portfolio/templates/portfolio/landing_page.html
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" media="print" onload="this.media='all'">
    <script src="{% static 'portfolio/js/scripts.js' %}" defer></script>
</head>
<body>
    <header>
        <nav role="navigation" aria-label="Main">
            <ul class="nav-actions">
                <li>
                    <a href="{% url 'autenticacao:login' %}" class="btn-login">
                        <img src="{% static 'portfolio/images/login_image.png' %}" alt="Login" class="login-image">
                    </a>
                </li>
                <ul class="nav-links">
                    <li><a href="{% url 'portfolio:mebyme' %}">MeByMe</a></li>
                    <li><a href="{% url 'portfolio:mebyme_tech' %}">WebSite</a></li>
                    <li><a href="{% url 'meteo:home' %}">Metereologia</a></li>
                </ul>
                    <li class="weather-icon">
                        <img src="{{ icon_url }}" alt="Ícone do Tempo" style="width: 60px; height: 60px;">
                    </li>
            </ul>
        </nav>
    </header>
    <main>
        <section class="hero" style="background: url('{% static 'portfolio/images/praia.jpg' %}') no-repeat center center/cover;">
            <div class="hero-text">
                <h1 class="portfolio-heading">Bem-vindo ao Meu Portfolio</h1>
                <div class="hero-buttons">
                    <a href="{% url 'bandas:bandas_list' %}" class="btn-primary">Bandas</a>
                    <a href="{% url 'LIG:index' %}" class="btn-secondary">Curso</a>
                    <a href="{% url 'artigos:layout' %}" class="btn-terceiro">Artigos</a>
                </div>
            </div>
        </section>
        <div id="weather-icon"></div>
        <div id="date-time"></div>
        <button id="dark-mode-toggle">Toggle Dark Mode</button>
    </main>
</body>
</html>

portfolio/templates/portfolio/mebyme.html
<!DOCTYPE html>
<html lang="pt">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Me By Me</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/mebyme_styles.css' %}">
    <script src="{% static 'portfolio/js/mebyme_scripts.js' %}" defer></script>
</head>
<body>
    <header>
        <nav>
            <ul class="nav-actions">
                <li>
                    <a href="{% url 'portfolio:landing_page' %}" class="btn-back">
                        <img src="{% static 'portfolio/images/back_icon.png' %}" alt="Back" class="back-image">
                    </a>
                </li>
            </ul>
        </nav>
    </header>
    <main class="container">
        <section class="sidebar">
            <div class="profile">
                <img src="{% static 'portfolio/images/profile_image.JPG' %}" alt="Fábio Tomé">
                <h2>Fábio Tomé</h2>
                <p>Data de nascimento: 10/03/2004</p>
                <p>Nacionalidade: Portuguesa</p>
                <p>Sexo: Masculino</p>
            </div>
            <div class="contact">
                <h3>CONTACTO</h3>
                <p>Moinhos da Funcheira,<br>  Lisboa, Portugal</p>
                <p><a href="mailto:fabio.tomee@gmail.com">fabio.tomee@gmail.com</a></p>
                <p><a href="tel:+351935461805">(+351) 935461805</a></p>
                <p><a href="https://www.instagram.com/fabiojtome/" target="_blank">Instagram</a></p>
            </div>
            <button id="dark-mode-toggle">Toggle Dark Mode</button>
        </section>
        <section class="main-content">
            <div class="section">
                <h2>Sobre Mim</h2>
                <p>Sou estudante de Informática e Gestão, atualmente estou a tirar o curso na Universidade Lusófona. Tenho muito gosto nas áreas de vendas e gestão, pois sempre apreciei os negócios e a interação com pessoas. Sou uma pessoa organizada, trabalho em equipa e consigo trabalhar bem sob pressão.</p>
            </div>
            <div class="section">
                <h2>Educação e Formação</h2>
                <p>Lisboa, Portugal</p>
                <p><strong>Informática de Gestão Universidade Lusófona</strong></p>
                <p>Endereço: Campo Grande 376, 1749-024 Lisboa, Lisboa, Portugal</p>
            </div>
            <div class="section">
                <h2>Experiência Profissional</h2>
                <p><strong>01/05/2022 – 29/07/2022</strong> Lisboa, Portugal</p>
                <p>Vendedor de fruta Marl</p>
                <ul>
                    <li>Relação com clientes</li>
                    <li>Organização e disposição da loja</li>
                </ul>
            </div>
            <div class="section">
                <h2>Competências Linguísticas</h2>
                <p><strong>Língua(s) Materna(s):</strong> Português</p>
                <p><strong>Outra(s) Língua(s):</strong> Inglês</p>
                <ul>
                    <li>Compreensão oral: C1</li>
                    <li>Leitura: C1</li>
                    <li>Produção oral: B1</li>
                    <li>Interação oral: B2</li>
                    <li>Escrever: B2</li>
                </ul>
            </div>
            <div class="section">
                <h2>Competências Digitais</h2>
                <p>Microsoft Office | Redes Sociais | Facilidade de Aprendizagem de Novos Softwares | Conhecimento básico em C#, Java, Kotlin, Python | Gosto pelo trabalho em equipa</p>
            </div>

        </section>
    </main>
</body>
</html>

portfolio/templates/portfolio/mebyme_tech.html
<html lang="pt">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tecnologias Aplicadas</title>
    <link rel="stylesheet" href="{% static 'portfolio/css/mebyme_tech_styles.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul class="nav-actions">
                <li>
                    <a href="{% url 'portfolio:landing_page' %}" class="btn-back">
                        <img src="{% static 'portfolio/images/back_icon.png' %}" alt="Back" class="back-image">
                    </a>
                </li>
            </ul>
        </nav>
    </header>
    <main class="container">
        <section class="hero" style="background: url('{% static 'portfolio/images/praia.jpg' %}') no-repeat center center/cover;">
            <div class="overlay"></div>
            <section class="main-content">
                <div class="section">
                    <h2>Tecnologias Utilizadas</h2>
                    <ul>
                        <li><strong>Django:</strong> Framework web em Python usado para desenvolver o site.</li>
                        <li><strong>HTML e CSS:</strong> Linguagens básicas para estrutura e estilo do site.</li>
                        <li><strong>JavaScript:</strong> Usado para interatividade, como o botão de alternar o modo escuro.</li>
                        <li><strong>Python:</strong> Linguagem de programação utilizada com Django para criar a lógica de backend do site.</li>
                        <li><strong>Git:</strong> Sistema de controle de versão para colaboração e controle de código-fonte.</li>
                        <li><strong>GitHub:</strong> Plataforma de hospedagem de código-fonte para o projeto.</li>
                    </ul>
                </div>
                <div class="section">
                    <h2>Estrutura do Projeto</h2>
                    <p>O projeto segue a estrutura padrão do Django, com os seguintes diretórios e componentes principais:</p>
                    <ul>
                        <li><strong>portfolio:</strong> Aplicação principal que contém as configurações do Django e as views.</li>
                        <li><strong>models:</strong> Definição das estruturas de dados e a interação com o banco de dados.</li>
                        <li><strong>views:</strong> Funções que gerenciam a lógica do aplicativo e retornam as respostas HTML.</li>
                        <li><strong>urls:</strong> Sistema de roteamento que direciona as URLs para as views correspondentes.</li>
                        <li><strong>loader:</strong> Funções ou classes usadas para carregar dados iniciais ou arquivos específicos.</li>
                        <li><strong>json:</strong> Utilizado para trabalhar com dados no formato JSON, especialmente em APIs e troca de dados assíncronos.</li>
                        <li><strong>static:</strong> Diretório para arquivos estáticos, como CSS, JS e imagens.</li>
                        <li><strong>templates:</strong> Diretório para os templates HTML usados no site.</li>
                        <li><strong>Visualização:</strong> <a href="https://youtu.be/yU4r3qhK54I" target="_blank">https://youtu.be/yU4r3qhK54I</a></li>

                    </ul>
                </div>
            </section>
        </section>
    </main>
</body>
</html>