LIG/urls.py
from django.urls import path
from . import views

app_name = 'LIG'

urlpatterns = [
    path('', views.index, name='index'),
    path('cursos/', views.cursos_list, name='cursos_list'),
    path('curso/<int:curso_id>/', views.curso_detail, name='curso_detail'),
    path('disciplinas/', views.disciplinas_list, name='disciplinas_list'),
    path('disciplina/<int:disciplina_id>/', views.disciplina_detail, name='disciplina_detail'),
    path('projeto/<int:projeto_id>/', views.projeto_detail, name='projeto_detail'),
    path('cursos/novo', views.novo_curso_view,name="novo_curso"),
    path('cursos/<int:curso_id>/edita', views.edita_curso_view,name="edita_curso"),
    path('cursos/<int:curso_id>/apaga', views.apaga_curso_view,name="apaga_curso"),
]

autenticacao/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'autenticacao'


urlpatterns = [
    path('registo/', views.registo_view, name="registo"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),


    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='registration/custom_password_reset_form.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='registration/custom_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/custom_password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/custom_password_reset_complete.html'), name='password_reset_complete'),
]

bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'

urlpatterns = [
    path('', views.bandas_list, name='bandas_list'),
    path('banda/<int:pk>/', views.banda_detail, name='banda'),
    path('album/<int:pk>/', views.album_detail, name='album'),
    path('banda/novo/', views.bandas_create, name='banda_create'),
    path('banda/editar/<int:pk>/', views.bandas_update, name='banda_update'),
    path('banda/excluir/<int:pk>/', views.bandas_delete, name='banda_delete'),
    path('album/novo/', views.albuns_create, name='album_create'),
    path('album/editar/<int:pk>/', views.albuns_update, name='album_update'),
    path('album/excluir/<int:pk>/', views.albuns_delete, name='album_delete'),
    path('musica/novo/', views.musicas_create, name='musica_create'),
    path('musica/editar/<int:pk>/', views.musicas_update, name='musica_update'),
    path('musica/excluir/<int:pk>/', views.musicas_delete, name='musica_delete'),
    path('capa-fundo/', views.capa_fundo_update, name='capa_fundo_update'),
]

python_inicio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('novaapp/', include('novaapp.urls')),
    path('bandas/',include('bandas.urls')),
    path('artigos/',include('artigos.urls')),
    path('festivais/',include('festivais.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('LIG/', include('LIG.urls')),
    path('portfolio', include('portfolio.urls')),
    path('meteo', include('meteo.urls')),

]

bandas/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, URLValidator
from datetime import datetime
from django.utils.translation import gettext_lazy as _

class Bandas(models.Model):
    nome = models.CharField(max_length=100)
    nacionalidade = models.CharField(max_length=100)
    ano_criacao = models.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(datetime.now().year)])
    foto = models.ImageField(upload_to='banda_fotos/')
    bio = models.TextField()

    def __str__(self):
        return self.nome


class Albuns(models.Model):
    titulo = models.CharField(max_length=100)
    ano_lancamento = models.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(datetime.now().year)])
    foto = models.ImageField(upload_to='banda_fotos/', blank=True)
    capa = models.ImageField(upload_to='capa_fotos/', blank=True)
    banda = models.ForeignKey(Bandas, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo


class Musicas(models.Model):
    titulo = models.CharField(max_length=100)
    duracao = models.TimeField()
    link = models.URLField(blank=True, validators=[URLValidator()])
    album = models.ForeignKey(Albuns, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo


class Capafundo(models.Model):
    nome = models.CharField(max_length=100,blank=True)
    foto = models.ImageField(upload_to='capas_fundo/',blank=True)

    def __str__(self):
        return self.nome

bandas/forms.py
from django import forms
from .models import Bandas, Albuns, Musicas

class BandaForm(forms.ModelForm):
    class Meta:
        model = Bandas
        fields = ['nome', 'nacionalidade', 'ano_criacao', 'foto', 'bio']

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Albuns
        fields = ['titulo', 'ano_lancamento', 'foto', 'capa', 'banda']

class MusicaForm(forms.ModelForm):
    class Meta:
        model = Musicas
        fields = ['titulo', 'duracao', 'link', 'album']




class AlbunsForm(forms.ModelForm):
    class Meta:
        model = Albuns
        fields = ['titulo', 'ano_lancamento', 'foto', 'capa']  # Adicione outros campos conforme necessário

    def __init__(self, banda, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.banda = banda

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.banda = self.banda
        if commit:
            instance.save()
        return instance

bandas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound
from .models import Bandas, Albuns, Musicas
from .forms import BandaForm, AlbumForm, MusicaForm
from django.views.generic.edit import UpdateView
from .forms import AlbunsForm





def bandas_list(request):
    bandas = Bandas.objects.all()
    return render(request, 'bandas/index.html', {'bandas': bandas})

def banda_detail(request, pk):
    try:
        banda = Bandas.objects.get(pk=pk)
    except Bandas.DoesNotExist:
        return HttpResponseNotFound("Banda não encontrada")
    return render(request, 'bandas/banda.html', {'banda': banda})

def album_detail(request, pk):
    try:
        album = Albuns.objects.get(pk=pk)
    except Albuns.DoesNotExist:
        return HttpResponseNotFound("Álbum não encontrado")
    return render(request, 'bandas/album.html', {'album': album})

# Views para criação, edição e exclusão de bandas, álbuns e músicas
def bandas_create(request):
    if request.method == 'POST':
        form = BandaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('bandas:bandas_list')
    else:
        form = BandaForm()
    return render(request, 'bandas/form_banda.html', {'form': form})

def bandas_update(request, pk):
    try:
        banda = Bandas.objects.get(pk=pk)
    except Bandas.DoesNotExist:
        return HttpResponseNotFound("Banda não encontrada")

    if request.method == 'POST':
        form = BandaForm(request.POST, request.FILES, instance=banda)
        if form.is_valid():
            form.save()
            return redirect('bandas:banda', pk=pk)
    else:
        form = BandaForm(instance=banda)
    return render(request, 'bandas/form_banda.html', {'form': form})

def bandas_delete(request, pk):
    try:
        banda = Bandas.objects.get(pk=pk)
    except Bandas.DoesNotExist:
        return HttpResponseNotFound("Banda não encontrada")

    if request.method == 'POST':
        banda.delete()
        return redirect('bandas:bandas_list')
    return render(request, 'bandas/confirm_delete.html', {'object': banda})

def albuns_create(request):
    banda_id = request.GET.get('banda')
    try:
        banda = Bandas.objects.get(pk=banda_id)
    except Bandas.DoesNotExist:
        return HttpResponseNotFound("Banda não encontrada")

    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            album = form.save(commit=False)
            album.banda = banda
            album.save()
            return redirect('bandas:banda', pk=banda.id)
    else:
        form = AlbumForm()
    return render(request, 'bandas/form_album.html', {'form': form, 'banda': banda})

def albuns_update(request, pk):
    album = Albuns.objects.get(pk=pk)
    banda = album.banda  # Obtém a banda associada ao álbum
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES, instance=album)
        if form.is_valid():
            form.save()
            return redirect('bandas:banda', pk=banda.pk)  # Redireciona para a página da banda após a edição
    else:
        form = AlbumForm(instance=album)
    return render(request, 'bandas/form_album.html', {'form': form, 'banda': banda})

def albuns_delete(request, pk):
    try:
        album = Albuns.objects.get(pk=pk)
    except Albuns.DoesNotExist:
        return HttpResponseNotFound("Álbum não encontrado")

    if request.method == 'POST':
        album.delete()
        return redirect('bandas:banda', pk=album.banda.id)
    return render(request, 'bandas/confirm_delete.html', {'object': album})

def musicas_create(request):
    album_id = request.GET.get('album')
    try:
        album = Albuns.objects.get(pk=album_id)
    except Albuns.DoesNotExist:
        return HttpResponseNotFound("Álbum não encontrado")

    if request.method == 'POST':
        form = MusicaForm(request.POST)
        if form.is_valid():
            musica = form.save(commit=False)
            musica.album = album
            musica.save()
            return redirect('bandas:album', pk=album.id)
    else:
        form = MusicaForm()
    return render(request, 'bandas/form_musica.html', {'form': form, 'album': album})

def musicas_update(request, pk):
    musica = Musicas.objects.get(pk=pk)
    album = musica.album  # Obtém o álbum associado à música
    if request.method == 'POST':
        form = MusicaForm(request.POST, request.FILES, instance=musica)
        if form.is_valid():
            form.save()
            return redirect('bandas:album', pk=album.pk)  # Redireciona para a página do álbum após a edição
    else:
        form = MusicaForm(instance=musica)
    return render(request, 'bandas/form_musica.html', {'form': form, 'album': album})


def musicas_delete(request, pk):
    try:
        musica = Musicas.objects.get(pk=pk)
    except Musicas.DoesNotExist:
        return HttpResponseNotFound("Música não encontrada")

    if request.method == 'POST':
        musica.delete()
        return redirect('bandas:album', pk=musica.album.id)
    return render(request, 'bandas/confirm_delete.html', {'object': musica})

def capa_fundo_update(request):
    try:
        capa_fundo = CapaFundo.objects.get(pk=1)
    except CapaFundo.DoesNotExist:
        return HttpResponseNotFound("Capa de fundo não encontrada")

    if request.method == 'POST':
        form = CapaFundoForm(request.POST, request.FILES, instance=capa_fundo)
        if form.is_valid():
            form.save()
            return redirect('bandas:bandas_list')
    else:
        form = CapaFundoForm(instance=capa_fundo)
    return render(request, 'bandas/form_capa_fundo.html', {'form': form})


class AlbunsUpdateView(UpdateView):
    model = Albuns
    fields = ['titulo', 'ano_lancamento', 'foto', 'capa']  # Adicione outros campos conforme necessário
    template_name = 'bandas/form_album.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['banda'] = self.object.banda  # Passa a banda para o contexto do template
        return context



def album_create(request, banda_id):
    banda = Banda.objects.get(id=banda_id)
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES, banda=banda)
        if form.is_valid():
            form.save()
            # Redirecionar ou fazer outras operações após a criação do álbum
    else:
        form = AlbunsForm(banda=banda)
    return render(request, 'bandas/form_album.html', {'form': form, 'banda': banda})

bandas/templates/bandas/album.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <div class="album-details">
        <h2>{{ album.titulo }}</h2>
        <p>Ano de Lançamento: {{ album.ano_lancamento }}</p>
        {% if album.foto %}
            <p><img src="{{ album.foto.url }}" alt="Foto do álbum"></p>
        {% else %}
            <p>Foto do álbum não disponível</p>
        {% endif %}

        <h3>Músicas:</h3>
        <ul>
            {% for musica in album.musicas_set.all %}
                <li>
                    {{ musica.titulo }} - Duração: {{ musica.duracao }}
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'bandas:musica_update' musica.id %}">Editar</a>
                        <a href="{% url 'bandas:musica_delete' musica.id %}">Apagar</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'bandas:banda' album.banda.id %}">Voltar para Banda</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'bandas:musica_create' %}?album_id={{ album.id }}"><button>Inserir nova Música</button></a>
        {% endif %}
    </div>
    <style>
        .album-details {
            background-color: rgba(0, 0, 0, 0.8);
            padding: 20px;
            border-radius: 10px;
            margin: 20px auto;
            max-width: 600px;
        }
        .album-details img {
            max-width: 100%;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .album-details ul {
            list-style-type: none;
            padding: 0;
        }
        .album-details li {
            margin-bottom: 10px;
        }
        .album-details a {
            color: white;
            text-decoration: none;
            margin-right: 10px;
            transition: color 0.3s ease;
        }
        .album-details a:hover {
            color: #1DB954;
        }
        .album-details button {
            background-color: #1DB954;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .album-details button:hover {
            background-color: #1ed760;
        }
    </style>
{% endblock %}

bandas/templates/bandas/banda.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <div class="banda-details">
        <h2>{{ banda.nome }}</h2>
        <p>Nacionalidade: {{ banda.nacionalidade }}</p>
        <p>Ano de Criação: {{ banda.ano_criacao }}</p>
        {% if banda.foto %}
            <p><img src="{{ banda.foto.url }}" alt="Foto da banda"></p>
        {% else %}
            <p>Foto da banda não disponível</p>
        {% endif %}
        <p>{{ banda.bio }}</p>
        <h3>Álbuns:</h3>
        <ul>
            {% for album in banda.albuns_set.all %}
                <li>
                    <a href="{% url 'bandas:album' album.id %}">{{ album.titulo }}</a>
                    <span class="edit-delete">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'bandas:album_update' album.id %}">Editar</a>
                            <a href="{% url 'bandas:album_delete' album.id %}">Apagar</a>
                        {% endif %}
                    </span>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'bandas:bandas_list' %}">Voltar para Bandas</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'bandas:album_create' %}?banda_id={{ banda.id }}"><button>Inserir novo Álbum</button></a>
        {% endif %}
    </div>
    <style>
        .banda-details {
            background-color: rgba(0, 0, 0, 0.8);
            padding: 20px;
            border-radius: 10px;
            margin: 20px auto;
            max-width: 600px;
        }
        .banda-details img {
            max-width: 100%;
            border-radius: 5px;
            margin-bottom: 10px;
        }
        .banda-details ul {
            list-style-type: none;
            padding: 0;
        }
        .banda-details li {
            margin-bottom: 10px;
            display: flex;
            align-items: center;
        }
        .banda-details .edit-delete {
            margin-left: auto;
        }
        .banda-details a {
            color: white;
            text-decoration: none;
            margin-right: 10px;
            transition: color 0.3s ease;
        }
        .banda-details a:hover {
            color: #1DB954;
        }
        .banda-details button {
            background-color: #1DB954;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .banda-details button:hover {
            background-color: #1ed760;
        }
    </style>
{% endblock %}

bandas/templates/bandas/confirm_delete.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h2>Confirmar exclusão</h2>
    <p>Tem certeza de que deseja excluir "{{ object }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Sim, excluir</button>
    </form>
    <a href="{% url 'bandas:bandas_list' %}">Cancelar</a>
{% endblock %}

bandas/templates/bandas/form_album.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h2>{{ form.instance.pk|yesno:"Editar Álbum,Novo Álbum" }}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
    <a href="{% url 'bandas:banda' banda.id %}">Cancelar</a>
{% endblock %}

bandas/templates/bandas/form_banda.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h2>{{ form.instance.pk|yesno:"Editar Banda,Nova Banda" }}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
    <a href="{% url 'bandas:bandas_list' %}">Cancelar</a>
{% endblock %}

bandas/templates/bandas/form_musica.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <h2>{{ form.instance.pk|yesno:"Editar Música,Nova Música" }}</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Salvar</button>
    </form>
    <a href="{% url 'bandas:album' album.id %}">Cancelar</a>
{% endblock %}

bandas/templates/bandas/index.html
{% extends 'bandas/layout.html' %}

{% block content %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <div class="bandas-list">
        <h2>Bandas</h2>
        <ul>
            {% for banda in bandas %}
                <li>
                    <a href="{% url 'bandas:banda' banda.id %}">{{ banda.nome }}</a>
                    <span class="edit-delete">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'bandas:banda_update' banda.id %}" style="color: lightblue;">Editar</a>
                            <a href="{% url 'bandas:banda_delete' banda.id %}" style="color: red;">Apagar</a>
                        {% endif %}
                    </span>
                </li>
            {% endfor %}
        </ul>
        {% if request.user.is_authenticated %}
            <a href="{% url 'bandas:banda_create' %}"><button>Inserir nova Banda</button></a>
        {% endif %}
    </div>
    <style>
        .bandas-list {
            background-color: rgba(0, 0, 0, 0.8);
            padding: 20px;
            border-radius: 10px;
            margin: 20px auto;
            max-width: 600px;
        }
        .bandas-list ul {
            list-style-type: none;
            padding: 0;
        }
        .bandas-list li {
            margin-bottom: 10px;
            display: flex;
            align-items: center;
        }
        .bandas-list .edit-delete {
            margin-left: auto;
        }
        .bandas-list a {
            color: white;
            text-decoration: none;
            margin-right: 10px;
            transition: color 0.3s ease;
        }
        .bandas-list a:hover {
            color: #1DB954;
        }
        .bandas-list button {
            background-color: #1DB954;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }
        .bandas-list button:hover {
            background-color: #1ed760;
        }
    </style>
{% endblock %}

bandas/templates/bandas/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <title>{% block title %}Bandas{% endblock %}</title>
    <style>
        body {
            background-image: url("{% static 'capas_fundo/foto.jpg' %}");
            background-size: cover;
            background-repeat: no-repeat;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: rgba(0, 0, 0, 0.8);
            color: white;
            padding: 20px;
            text-align: center;
        }
        main {
            padding: 20px;
            color: white;
        }
        a {
            color: white;
            text-decoration: none;
            margin-right: 10px;
        }
    </style>
</head>
<body>
    <header>
        <h1>Menu</h1>
        {% if request.user.is_authenticated %}
            <a href="{% url 'autenticacao:logout' %}?next={{ request.path }}">Logout</a>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" style="width:2ch; height:2ch;">
                <path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/>
            </svg>
            {{ request.user.username }}
        {% else %}
            <a href="{% url 'autenticacao:login' %}"><button>Login</button></a>
        {% endif %}
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>